version: '3.7'
services:
  database:
    container_name: roach
    hostname: roach
    restart: always
    image: 'cockroachdb/cockroach:latest'
    command: start --insecure
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - database
    volumes:
      - '${PWD}/cockroach-data/roach:/cockroach/cockroach-data'
      - '${PWD}/sql_scripts:/sql_scripts'
  api:
    container_name: api
    hostname: bugbrother
    restart: always
    build:
      context: api
    image: 'covid-test-db/api:latest'
    ports:
      - 5000:5000
    networks:
      - database
      - api
  ui:
    container_name: ui
    hostname: magnifyingglass
    restart: always
    build:
      context: ui
    image: 'covid-test-db/ui:latest'
    ports:
      - 5001:8080
    networks:
      - api
networks:
  admin:
    name: admin
  database:
    name: database
    driver: bridge
  api:
    name: api
